version: '4'
services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    environment:
      - 'MONGO_INITDB_DATABASE=product-service'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017'
    volumes:
        - './docker/mongodb/data:/data/db'
